### PR TITLE
Fix broken links in conformance section  #122

### PR DESCRIPTION
**Pull request by m-burgoyne**

### CODE REVIEW

**Comment by m-burgoyne** [comment]
@dblodgett-usgs  -- other parts of the document still had references to the corridor query, so I included the corridor query in the conformance section

**Comment by dblodgett-usgs** [comment]
hmm... ok. @chris-little what do you think?

**Comment by dblodgett-usgs** [comment]
Going to merge in preparation for public comment.

**Comment by chris-little** [comment]
We had simple corridor in. We had long discussions about specifying different width/depth UoM. We left out interpolation/resolution .

**Pull request merged**
