### PR TITLE
Replace obsolete parameter names

### PR DESCRIPTION
**Pull request by m-burgoyne**
Fixes for #147 and #146 and text updated in Corridor and Trajectory descriptions

### CODE REVIEW

**Review by chris-little — COMMENTED** [review]
outputFormat good.
Most of time to datetime good, but there are some places, when referring to time in WKT string , which is Unix time, not an ISO8601 datetime, should be left as time.

**Comment by m-burgoyne** [comment]
Fixes for #150

**Review by chris-little — COMMENTED** [review]
Much better! Spotted a few typos from a long time ago ('att') and 'height units will height units'

**Comment by chris-little** [comment]
@m-burgoyne Are you up for including correcting parentheses in WKT examples for area, cube etc. Some are missing, and some are doubled.
1. Radius multipoint examples
2. Area polygon examples
3. Cube polygon examples
It is getting late!

**Review by chris-little — APPROVED** [review]
Looks good!

**Comment by m-burgoyne** [comment]
Added fixes for Issue #151

**Comment by m-burgoyne** [comment]
Updated the extent schema to add a name field to the coordinate reference systems , this should help mitigate one of the issues identified in the code sprint by allowing the inclusion of descriptive labels to the coordinate reference systems used by the collection.

**Review by chris-little — APPROVED** [review]
changes all good after three edits in place

**Review by dblodgett-usgs — APPROVED** [review]

**Comment by dblodgett-usgs** [comment]
Going to merge so hopefully we have a fresh build in the morning.

**Pull request merged**
