### PR TITLE
Add link examples to OpenAPI schemas

### PR DESCRIPTION
**Pull request by m-burgoyne**
Fix for https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/11

### CODE REVIEW

**Review by chris-little — COMMENTED** [review]
Looks Ok. Will merge when JSON->YAML changes made in examples

**Comment by m-burgoyne** [comment]
Files modified to change incorrect references from JSON to YAML

**Review by chris-little — COMMENTED** [review]
Looks Good. Assuming the replacement of minItems=2, maxItems=2 with just minItems=1 is correct, so there could be more than two time items?

**Comment by m-burgoyne** [comment]
Updated to reflect the changes made to the sprint 2 branch

**Comment by m-burgoyne** [comment]
Added fixes for sprint 2 issues:

https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/28
https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/29

**Review by chris-little — APPROVED** [review]

**Comment by chris-little** [comment]
Merge to get full copy by tomorrow.

**Pull request merged**
