### PR TITLE
Add GeoJSON Schema from Code Sprint

### PR DESCRIPTION
**Pull request by m-burgoyne**
Updated to include the GeoJSON changes created by the  Items view of EDR resources.( [ Code Sprint Issue #12)](https://github.com/opengeospatial/EDR-API-Sprint/issues/12).  Also removes the workflow file as it is no longer required to generate the PDF and HTML docs

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Can we also remove package-lock.json and any other dependencies of the workflow?

**Comment by m-burgoyne** [comment]
Removed the obsolete packaging files

**Comment by dblodgett-usgs** [comment]
👍 -- glancing through the rest of this it looks good. So you are thinking some of this would be refactored into a `location` endpoint rather than `items` pending the discussion of #28 ?

**Comment by m-burgoyne** [comment]
Yes, the next focus will be to tidy up the response definitions for the querys.

**Comment by dblodgett-usgs** [comment]
Great. Thanks!

**Pull request merged**
